#ifndef DATABASEUI_GLOBAL_H
#define DATABASEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEUI_LIBRARY)
#  define DATABASEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEUISHARED_EXPORT Q_DECL_IMPORT
#endif


#ifdef STATICBUILD
#define DATABASEUISHARED_EXPORT
#endif

#endif // DATABASEUI_GLOBAL_H
