#ifndef STATISTICSUI_GLOBAL_H
#define STATISTICSUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTICSUI_LIBRARY)
#  define STATISTICSUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTICSUISHARED_EXPORT Q_DECL_IMPORT
#endif


#ifdef STATICBUILD
#define STATISTICSUISHARED_EXPOR
#endif


#endif // STATISTICSUI_GLOBAL_H
