#ifndef LIBLOGVIEWER_GLOBAL_H
#define LIBLOGVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBLOGVIEWER_LIBRARY)
#  define LIBLOGVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBLOGVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBLOGVIEWER_GLOBAL_H
